# Use Node.js LTS image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Install Firebase CLI
RUN npm install -g firebase-tools

# Copy necessary files for Firebase setup
COPY ./firebase.json ./
COPY ./firestore.rules ./
COPY ./firebase.json ./
COPY ./firestore.indexes.json ./

# Expose ports for the Firebase emulator
EXPOSE 4000 8080 5000 9000

# Start the Firebase emulator
CMD ["firebase", "emulators:start"]
